-- Adds audit action types for the new Users/Roles administration pages.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_UNLOCKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ROLE_PERMISSIONS_UPDATED';
